// Search
export const REQUEST_SEARCH_RESULTS = 'REQUEST_SEARCH_RESULTS';
export const RECEIVE_SEARCH_RESULTS = 'RECEIVE_SEARCH_RESULTS';

// List
export const SAVE_SPACE_PROFILE = 'SAVE_SPACE_PROFILE';

// Manage account
export const REQUEST_USER_PROFILE = 'REQUEST_USER_PROFILE';
export const RECEIVE_USER_PROFILE = 'RECEIVE_USER_PROFILE';
export const SAVE_USER_PROFILE = 'SAVE_USER_PROFILE';
